/**
 * Product examples (auto-generated by /extension create)
 * - 列出所有 + filter
 */

// Product 型別 (auto-generated from spec.json)
export interface Product {
  id: string;
  createdAt: string;
  updatedAt: string;
  [key: string]: unknown;
}

export async function listAll(): Promise<Product[]> {
  const res = await fetch('/api/crud/product');
  return (await res.json()).items;
}

export async function filterByName(name: string): Promise<Product[]> {
  const res = await fetch(`/api/crud/product?name=${encodeURIComponent(name)}`);
  return (await res.json()).items;
}
