/**
 * Product beforeCreate hook (auto-generated by /extension create)
 * - 設定 createdAt / updatedAt
 */

// Product 型別 (auto-generated from spec.json)
export interface Product {
  id: string;
  createdAt: string;
  updatedAt: string;
  [key: string]: unknown;
}

export async function beforeCreate(data: Partial<Product>): Promise<Partial<Product>> {
  const now = new Date().toISOString();
  return {
    ...data,
    createdAt: now,
    updatedAt: now,
  };
}
