/**
 * Sprint 55 Stage 55-1 (FR-22.1 + FR-22.2) — Extension Template Generator
 *
 * 對應 PRD: docs/prd/11-chat-v2-completions.md §2.15 (FR-20.x)
 * 對應 Plan Gate: docs/sprint55-plan-gate.md
 * 對應 Design Gate: docs/sprint55-design-gate.md
 *
 * 設計 (A 路線, 固定 8 檔案模板):
 * - 不實際呼叫 LLM (Sprint 56+ 疊加 B 路線)
 * - 用固定 8 檔案模板 + admin 指定 fields 動態生成
 * - 沿用 todo extension 結構 (已被 Sprint 12+ 驗證)
 */

import type { ExtensionFile } from './extension-validator';

// ==============================================
// 1. Field type 推斷 (FR-22.2.1)
// ==============================================

export type FieldType = 'string' | 'text' | 'boolean' | 'datetime' | 'enum' | 'number';

/**
 * 從 field 名稱推斷 type
 * - *Date / *date → datetime
 * - is* / has* / *Completed → boolean
 * - price / amount / count / stock / quantity → number
 * - description / content / notes / text → text
 * - 其他 → string
 */
export function inferFieldType(fieldName: string): FieldType {
  const lower = fieldName.toLowerCase();

  // datetime
  if (/date$/i.test(lower)) return 'datetime';
  if (/at$/i.test(lower)) return 'datetime'; // publishedAt, createdAt 等
  if (lower === 'datetime') return 'datetime';

  // boolean
  if (/^(is|has)/.test(lower)) return 'boolean';
  if (/completed$/i.test(lower)) return 'boolean';

  // number
  const numberKeywords = ['price', 'amount', 'count', 'stock', 'quantity', 'total', 'age', 'score', 'rating'];
  if (numberKeywords.some((k) => lower.includes(k))) return 'number';

  // text
  const textKeywords = ['description', 'content', 'notes', 'bio', 'text', 'summary'];
  if (textKeywords.some((k) => lower.includes(k))) return 'text';

  return 'string';
}

export interface FieldSpec {
  name: string;
  type: FieldType;
  label: string;
}

export function inferFields(fieldNames: string[]): FieldSpec[] {
  return fieldNames.map((name) => ({
    name,
    type: inferFieldType(name),
    label: name.charAt(0).toUpperCase() + name.slice(1).replace(/([A-Z])/g, ' $1'),
  }));
}

// ==============================================
// 2. ExtensionTemplate.generate() (FR-22.1.1)
// ==============================================

export interface ExtensionTemplateInput {
  name: string;
  fields: string[];
  force?: boolean;
}

export interface ExtensionTemplateOutput {
  files: ExtensionFile[];
}

const HOOK_BEFORE_CREATE_TEMPLATE = `/**
 * {modelName} beforeCreate hook (auto-generated by /extension create)
 * - 設定 createdAt / updatedAt
 */

// {modelName} 型別 (auto-generated from spec.json)
export interface {modelName} {
  id: string;
  createdAt: string;
  updatedAt: string;
  [key: string]: unknown;
}

export async function beforeCreate(data: Partial<{modelName}>): Promise<Partial<{modelName}>> {
  const now = new Date().toISOString();
  return {
    ...data,
    createdAt: now,
    updatedAt: now,
  };
}
`;

const ACTION_COMPLETE_TEMPLATE = `/**
 * {modelName} complete action (auto-generated by /extension create)
 * - 切換 completed 狀態
 */

// {modelName} 型別 (auto-generated from spec.json)
export interface {modelName} {
  id: string;
  createdAt: string;
  updatedAt: string;
  [key: string]: unknown;
}

export async function complete(item: {modelName}): Promise<{modelName}> {
  return {
    ...item,
    completed: !item.completed,
    updatedAt: new Date().toISOString(),
  };
}
`;

const COMPUTED_REMAINING_DAYS_TEMPLATE = `/**
 * {modelName} remainingDays computed (auto-generated by /extension create)
 * - 計算距 dueDate 剩餘天數
 */

// {modelName} 型別 (auto-generated from spec.json)
export interface {modelName} {
  id: string;
  dueDate?: string;
  createdAt: string;
  updatedAt: string;
  [key: string]: unknown;
}

export function remainingDays(item: {modelName}): number {
  if (!item.dueDate) return 0;
  const due = new Date(item.dueDate).getTime();
  const now = Date.now();
  return Math.ceil((due - now) / (1000 * 60 * 60 * 24));
}
`;

const WORKFLOW_TEMPLATE = `/**
 * {modelName} workflow (auto-generated by /extension create)
 * - draft → published 狀態機
 */

// {modelName} 型別 (auto-generated from spec.json)
export interface {modelName} {
  id: string;
  state?: string;
  createdAt: string;
  updatedAt: string;
  [key: string]: unknown;
}

export type {modelName}State = 'draft' | 'published';

const TRANSITIONS: Record<{modelName}State, {modelName}State[]> = {
  draft: ['published'],
  published: ['draft'],
};

export function canTransition(from: {modelName}State, to: {modelName}State): boolean {
  return TRANSITIONS[from]?.includes(to) ?? false;
}

export function transition(item: {modelName}, to: {modelName}State): {modelName} {
  if (!canTransition((item.state ?? 'draft') as {modelName}State, to)) {
    throw new Error(\`Cannot transition from \${item.state} to \${to}\`);
  }
  return {
    ...item,
    state: to,
    updatedAt: new Date().toISOString(),
  };
}
`;

const EXAMPLE_TEMPLATE = `/**
 * {modelName} examples (auto-generated by /extension create)
 * - 列出所有 + filter
 */

// {modelName} 型別 (auto-generated from spec.json)
export interface {modelName} {
  id: string;
  createdAt: string;
  updatedAt: string;
  [key: string]: unknown;
}

export async function listAll(): Promise<{modelName}[]> {
  const res = await fetch('/api/crud/{name}');
  return (await res.json()).items;
}

export async function filterByName(name: string): Promise<{modelName}[]> {
  const res = await fetch(\`/api/crud/{name}?name=\${encodeURIComponent(name)}\`);
  return (await res.json()).items;
}
`;

const README_TEMPLATE = `# {label} Extension

> Auto-generated by \`/extension create {name}\` (Sprint 55)

## 簡介

{label} 是一個 CRUD extension，提供基本的新增、查詢、更新、刪除功能。

## 欄位

{fieldsTable}

## Hooks

- \`{name}.beforeCreate\` — 自動設定 createdAt / updatedAt

## Actions

{actionsList}

## Computed

{computedList}

## Workflow

- draft → published 狀態機

## API

- \`GET /api/crud/{name}\` — 列出所有
- \`POST /api/crud/{name}\` — 新增
- \`GET /api/crud/{name}/[id]\` — 取得單筆
- \`PATCH /api/crud/{name}/[id]\` — 更新
- \`DELETE /api/crud/{name}/[id]\` — 刪除
`;

/**
 * FR-22.1.1: 產生 8 個檔案內容
 */
export function generateExtensionTemplate(input: ExtensionTemplateInput): ExtensionTemplateOutput {
  const { name, fields } = input;
  const fieldsList = inferFields(fields);
  const fieldsListWithAuto = [
    ...fieldsList,
    { name: 'createdAt', type: 'datetime' as FieldType, label: '建立時間' },
    { name: 'updatedAt', type: 'datetime' as FieldType, label: '更新時間' },
  ];

  const modelName = name.charAt(0).toUpperCase() + name.slice(1);
  const label = name.charAt(0).toUpperCase() + name.slice(1).replace(/-/g, ' ');
  const hasCompleted = fieldsList.some((f) => f.type === 'boolean');
  const hasDueDate = fieldsList.some((f) => f.type === 'datetime' && /date/i.test(f.name));

  const files: ExtensionFile[] = [];

  // 1. manifest.json
  const manifest = {
    name,
    version: '1.0.0',
    label,
    description: `${label} extension (auto-generated by Sprint 55)`,
    author: 'ai-headless admin',
    hooks: [`${name}.beforeCreate`],
    actions: hasCompleted ? [`${name}.complete`] : [],
    computed: hasDueDate ? [`${name}.remainingDays`] : [],
    permissions: [`${name}.create`, `${name}.read`, `${name}.update`, `${name}.delete`],
    dependencies: [],
    nav: {
      path: `/admin/crud/${name}`,
      label,
      order: 100,
    },
  };
  files.push({
    path: `extensions/${name}/manifest.json`,
    content: JSON.stringify(manifest, null, 2),
  });

  // 2. <name>-spec.json (path ends with spec.json)
  const spec = {
    name,
    label,
    requiresExtension: name,
    list: {
      allowColumnToggle: true,
      defaultColumns: ['createdAt', 'updatedAt'],
      views: [{ type: 'table', label: '表格' }],
    },
    models: [
      {
        name: modelName,
        label,
        description: `${label} model`,
        fields: fieldsListWithAuto.map((f) => ({
          name: f.name,
          type: f.type,
          label: f.label,
          validation: f.name === 'createdAt' || f.name === 'updatedAt' ? {} : { required: f.name === 'name' || f.name === 'title' },
          list: { defaultVisible: true },
        })),
      },
    ],
  };
  files.push({
    path: `extensions/${name}/spec.json`,
    content: JSON.stringify(spec, null, 2),
  });

  // 3. hooks/beforeCreate.ts (validateExtensionFiles expects 'beforeCreate.ts' but Sprint 12 uses 'before-create.ts')
  // 沿用 todo extension 命名: before-create.ts
  files.push({
    path: `extensions/${name}/hooks/before-create.ts`,
    content: HOOK_BEFORE_CREATE_TEMPLATE
      .replaceAll('{name}', name)
      .replaceAll('{modelName}', modelName),
  });

  // 4. actions/complete.ts (optional)
  if (hasCompleted) {
    files.push({
      path: `extensions/${name}/actions/complete.ts`,
      content: ACTION_COMPLETE_TEMPLATE
        .replaceAll('{name}', name)
        .replaceAll('{modelName}', modelName),
    });
  } else {
    // 仍需一個檔案, 但內容標 stub
    files.push({
      path: `extensions/${name}/actions/complete.ts`,
      content: `// No 'completed' field — stub action\nexport {};\n`,
    });
  }

  // 5. computed/remainingDays.ts (optional, or stub)
  if (hasDueDate) {
    files.push({
      path: `extensions/${name}/computed/remaining-days.ts`,
      content: COMPUTED_REMAINING_DAYS_TEMPLATE
        .replaceAll('{name}', name)
        .replaceAll('{modelName}', modelName),
    });
  } else {
    files.push({
      path: `extensions/${name}/computed/remaining-days.ts`,
      content: `// No 'dueDate' field — stub computed\nexport {};\n`,
    });
  }

  // 6. workflow/<name>-workflow.ts
  files.push({
    path: `extensions/${name}/workflow/${name}-workflow.ts`,
    content: WORKFLOW_TEMPLATE
      .replaceAll('{name}', name)
      .replaceAll('{modelName}', modelName),
  });

  // 7. examples/list-and-filter.ts
  files.push({
    path: `extensions/${name}/examples/list-and-filter.ts`,
    content: EXAMPLE_TEMPLATE
      .replaceAll('{name}', name)
      .replaceAll('{modelName}', modelName),
  });

  // 8. README.md
  const fieldsTable = fieldsListWithAuto
    .map((f) => `| \`${f.name}\` | ${f.type} | ${f.label} |`)
    .join('\n');
  const actionsList = hasCompleted
    ? `- \`${name}.complete\` — 切換 completed 狀態`
    : '- (無，無 boolean 欄位)';
  const computedList = hasDueDate
    ? `- \`${name}.remainingDays\` — 計算距 dueDate 剩餘天數`
    : '- (無，無 dueDate 欄位)';

  files.push({
    path: `extensions/${name}/README.md`,
    content: README_TEMPLATE
      .replaceAll('{label}', label)
      .replaceAll('{name}', name)
      .replace('{fieldsTable}', fieldsTable)
      .replace('{actionsList}', actionsList)
      .replace('{computedList}', computedList),
  });

  return { files };
}