/**
 * Product complete action (auto-generated by /extension create)
 * - 切換 completed 狀態
 */

// Product 型別 (auto-generated from spec.json)
export interface Product {
  id: string;
  createdAt: string;
  updatedAt: string;
  [key: string]: unknown;
}

export async function complete(item: Product): Promise<Product> {
  return {
    ...item,
    completed: !item.completed,
    updatedAt: new Date().toISOString(),
  };
}
