/**
 * Product workflow (auto-generated by /extension create)
 * - draft → published 狀態機
 */

// Product 型別 (auto-generated from spec.json)
export interface Product {
  id: string;
  state?: string;
  createdAt: string;
  updatedAt: string;
  [key: string]: unknown;
}

export type ProductState = 'draft' | 'published';

const TRANSITIONS: Record<ProductState, ProductState[]> = {
  draft: ['published'],
  published: ['draft'],
};

export function canTransition(from: ProductState, to: ProductState): boolean {
  return TRANSITIONS[from]?.includes(to) ?? false;
}

export function transition(item: Product, to: ProductState): Product {
  if (!canTransition((item.state ?? 'draft') as ProductState, to)) {
    throw new Error(`Cannot transition from ${item.state} to ${to}`);
  }
  return {
    ...item,
    state: to,
    updatedAt: new Date().toISOString(),
  };
}
